### ISSUE TITLE
petstore.yaml contains unnessesary quotes

### ISSUE THREAD

**Issue by kvlahromei** [swagger-api/rails-petstore#11]
Hi, the YAML file seems to contain to much quotes: http://petstore.swagger.io/v2/swagger.yaml
I'm not sure if this breaks any syntax (don't think so) but IMHO it should be in sync with the YAML represantation that you can get by the JSON file .

**Comment by webron** [comment]
a - why did you open it here?
b - the quotes are irrelevant.

**Comment by kvlahromei** [comment]
Sorry, I wasn't aware that this is the wrong place because I expected this to be the project of petstore.swagger.io.
I agree that it's just an minor case, but as it has some influence in the syntax highlightnig, it might be easy to fix and relevant?

**Comment by webron** [comment]
The petstore.swagger.io is derived from one of the samples in swagger-core.

It has influence of syntax highlighting where?

**Comment by kvlahromei** [comment]
Syntax highlightning for example over at http://editor.swagger.io

**Comment by webron** [comment]
That sounds more like an issue to open on [swagger-editor](https://github.com/swagger-api/swagger-editor) then as it should support it. If it's a valid YAML, it's a valid YAML.
